name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    - name: Set up MySQL
      run: |
        sudo apt-get update
        sudo apt-get install -y mysql-server
        sudo mysql -e "CREATE DATABASE IF NOT EXISTS foreign_student_match;"
        sudo mysql -e "CREATE DATABASE IF NOT EXISTS blotie_test;"
        sudo mysql -e "CREATE USER IF NOT EXISTS 'root'@'localhost' IDENTIFIED BY '1234';"
        sudo mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost';"
        sudo mysql -e "FLUSH PRIVILEGES;"

    - name: Set up environment variables
      run: |
        echo "AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }}" >> $GITHUB_ENV
        echo "AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }}" >> $GITHUB_ENV

    - name: Generate application.yml
      run: |
        echo "spring:
          datasource:
            url: jdbc:mysql://localhost:3306/foreign_student_match
            username: root
            password: 1234
            driver-class-name: com.mysql.cj.jdbc.Driver
          jpa:
            hibernate:
              ddl-auto: update
            properties:
              hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect

        cloud:
          aws:
            region:
              static: ap-southeast-2
            stack:
              auto: false
            s3:
              bucket: blotie
            credentials:
              access-key: ${{ secrets.AWS_ACCESS_KEY }}
              secret-key: ${{ secrets.AWS_SECRET_KEY }}" > src/main/resources/application.yml

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run application
      run: ./gradlew bootRun
