name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up AWS SAM
        uses: aws-actions/setup-sam@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-southeast-2

      - name: Generate application.yml
        run: |
          mkdir -p src/main/resources
          cat <<EOT > src/main/resources/application.yml
          spring:
            config:
              activate:
                on-profile: dev
            datasource:
              url: jdbc:mysql://localhost:3306/blotie_test
              username: root
              password: Ghkdwnsdud1!
              driver-class-name: com.mysql.cj.jdbc.Driver
            jpa:
              hibernate:
                ddl-auto: update
              properties:
                hibernate:
                  dialect: org.hibernate.dialect.MySQL8Dialect

          cloud:
            aws:
              region:
                static: ap-southeast-2
              stack:
                auto: false
              s3:
                bucket: blotie
              credentials:
                access-key: \${AWS_ACCESS_KEY}
                secret-key: \${AWS_SECRET_KEY}
          EOT

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run application
        run: ./gradlew bootRun
